[versions]
javierscGradlePlugins = "0.1.0-rc.19"
kotlin = "1.6.0"
kotlinBinaryValidator = "0.8.0"

[libraries]
javiersc-gradlePlugins-allPluginsX = { module = "com.javiersc.gradle-plugins:all-plugins", version.ref = "javierscGradlePlugins" }
jetbrains-kotlin-kotlinGradlePluginX = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
